services:
  - type: web
    name: cpa-shohag-pro-team
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: WS_PORT
        value: 28784
